---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: debian9
  - distro: debian8

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=true

  # Run tests.
  - ${PWD}/tests/test.sh

  # Setup test site.
  - 'docker exec ${container_id} mkdir -p /var/www/test'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
