---

- name: Downloads some pre defined yum repos - step 1.1
  get_url:
    url: "{{ item }}"
    dest: "/etc/yum.repos.d/"
  with_items: "{{ yum_repo_urls }}"
  when: ansible_os_family == 'RedHat'

- name: Downloads some pre defined yum repos - step 1.2
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{ yum_repo_key_urls }}"
  when: ansible_os_family == 'RedHat'

- name: Configurations before pre-packages are installed - step 1.3
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ pre_configs }}"

- name: Install pre packages - step 2.1
  package: "name={{ item }} state=installed"
  with_items: "{{ pre_packages }}"

- name: Configurations after pre packages are installed - step 2.2
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ pre_configs_after_install }}"

- name: Run some scripts before pre services are started - step 2.3
  script: "{{ item }}"
  with_items: "{{ scripts_before_pre_services }}"

- name: Start some services after pre packages are installed - step 2.4
  service: "name={{ item }} state=started"
  with_items: "{{ pre_services }}"

- name: Run some scripts after pre packages are installed - step 2.5
  script: "{{ item }}"
  with_items: "{{ scripts_after_pre_services}}"

- name: Install needed packages - step 3.1
  package: "name={{ item }} state=installed"
  with_items: "{{ to_be_installed_packages }}"

- name: Configurations after pre packages are installed - step 3.2
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ configs_after_install }}"

- name: Run some scripts after packages are installed - step 3.3
  script: "{{ item }}"
  with_items: "{{ scripts_before_services_started }}"

- name: Start some services after packages are installed - step 3.4
  service: "name={{ item }} state=started"
  with_items: "{{ started_services }}"

- name: Run some scripts after packages are installed and services are started - step 3.5
  script: "{{ item }}"
  with_items: "{{ scripts_after_services_started }}"

