---

- name: Step 1.1 - Download pre defined yum repos
  get_url:
    url: "{{ item }}"
    dest: "/etc/yum.repos.d/"
  with_items: "{{ yum_repo_urls }}"
  when: ansible_os_family == 'RedHat'

- name: Step 1.2 - Download pre defined rpm keys
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{ yum_repo_key_urls }}"
  when: ansible_os_family == 'RedHat'

- name: Step 1.3 - Update configuration before pre_packages are installed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ pre_configs }}"

- name: Step 2.1 - Install pre_packages
  package: "name={{ item }} state=installed"
  with_items: "{{ pre_packages }}"

- name: Step 2.2 - Update configuration after pre_packages are installed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ pre_configs_after_install }}"

- name: Step 2.3 - Run some scripts before pre services are started
  script: "{{ item }}"
  with_items: "{{ scripts_before_pre_services }}"

- name: Step 2.4 - Start services after pre_packages are installed
  service: "name={{ item }} state=started"
  with_items: "{{ pre_services }}"

- name: Step 2.5 - Run scripts after pre_packages are installed
  script: "{{ item }}"
  with_items: "{{ scripts_after_pre_services}}"

- name: Step 3.1 - Install desired_packages
  package: "name={{ item }} state=installed"
  with_items: "{{ desired_packages }}"

- name: Step 3.2 - Update configuration after desired_packages are installed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ configs_after_install }}"

- name: Step 3.3 - Run scripts after desired_packages are installed
  script: "{{ item }}"
  with_items: "{{ scripts_before_services_started }}"

- name: Step 3.4 - Start services after desired_packages are installed
  service: "name={{ item }} state=started"
  with_items: "{{ started_services }}"

- name: Step 3.5 - Run scripts after desired_packages are installed and services are started
  script: "{{ item }}"
  with_items: "{{ scripts_after_services_started }}"

